input UserInput {
  nome: String
  idade: Int
  salario: Float
  email: String
}

type User {
  idade: Int
  salario: Float
  nome: String
  id: ID
  email: String
  perfil: Perfil
}

type Query {
  usuario(id: Int): User
  usuarios: [User]
}

type Mutation {
  addUser(data: UserInput): User!
  updateUser(id: ID!, data: UserInput): User!
}
