input CreateContactInput {
  name: String
  email: String!
  telefone: String
}
input FiltroInout {
  id: Int
  email: String
}

type Contato {
  id: Int
  name: String
  email: String
  telefone: String
}

type Query {
  contatos: [Contato]
}

type Mutation {
  criarContato(data: CreateContactInput!): Contato!
  atualizarContato(id: Int!, data: CreateContactInput): Contato
  deletarContato(filtro: FiltroInout): Boolean
}
type Query {
  users: [Contato]
}
